[package]
name = "rust_mir_gen"
version = "0.1.0"
authors = ["cosine <trash@cosine.online>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
