[package]
name = "rsfg"
version = "0.1.0"
authors = ["Luna <lucidlyluna@gmail.com>"]
edition = "2018"

[dependencies]
indexmap = "1.0.2"
rvmfg = { version = "0.1.0", path = "../rvmfg" }
log = "0.4.6"
env_logger = "0.6.1"
docopt = "1.1.0"

[profile.release]
debug = true
